apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model
  name: model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  strategy: {}
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: noylevi/house-price-predictor:e33b4f8ed71874d1823c0ccc5a768b116b23a394
        name: house-price-predictor
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
